hw/mysite/member/urls.py
from django.conf.urls import url
from . import views

app_name = 'member'

urlpatterns = [
    url(r'^login/$', views.login, name='login'),
    url(r'^login/facebook/$', views.login_facebook, name='login_facebook'),
]

hw/mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'', include('video.urls')),
    url(r'^member/', include('member.urls')),
    url(r'^sns/', include('sns.urls')),
    url(r'^admin/', admin.site.urls),
]

hw/mysite/sns/urls.py
from django.conf.urls import url
from . import views

app_name = 'sns'
urlpatterns = [
    url(r'^(\d*)$', views.index, name='index'),
    url(r'^facebook/friends_ranking/$', views.friends_ranking, name='friends_ranking'),
    url(r'^facebook/save_friends/$', views.save_friends, name='save_friends'),
]

hw/mysite/video/urls.py
from django.conf.urls import url
from . import views

app_name = 'video'

urlpatterns = [
    url(r'^(\d*)$', views.main_list, name='main_list'),
    url(r'^cate/new/$', views.cate_new, name='cate_new'),
    url(r'^video/search/$', views.search, name='search'),
    url(r'^video/add/$', views.video_add, name='video_add'),
    url(r'^video/edit/(\d+)/$', views.video_edit, name='video_edit'),
]

hw/mysite/templates/common/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
  <title>Youtube bookmark</title>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="{% url 'video:main_list' ''%}">
          Youtube bookmark
        </a>
      </div>
      <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
        <li><span class="navbar-text">{{ user.email }}</span></li>
        {% else %}
        <li><a href="{% url 'member:login' %}">Login</a></li>
        {% endif %}
        <li><a href="{% url 'sns:index' ''%}">sns</a></li>
        <li><a href="{% url 'video:search' %}">Search</a></li>
      </ul>
    </div>
  </nav>

  <div class="container">
    {% if messages %}
    <div>
      {% for msg in messages %}
      <div class="alert
        {% if msg.level == DEFAULT_MESSAGE_LEVELS.DEBUG %}alert-info
        {% elif msg.level == DEFAULT_MESSAGE_LEVELS.INFO %}alert-info
        {% elif msg.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}alert-success
        {% elif msg.level == DEFAULT_MESSAGE_LEVELS.WARNING %}alert-warning
        {% elif msg.level == DEFAULT_MESSAGE_LEVELS.ERROR %}alert-danger
        {% endif %}" role="alert">
        {{ msg }}
      </div>
      {% endfor %}
    </div>
    {% endif %}
  </div>

{% block content %}
{% endblock %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
</body>
</html>