hw/mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'', include('video.urls')),
    url(r'^member/', include('member.urls')),
    url(r'^sns/', include('sns.urls')),
    url(r'^admin/', admin.site.urls),
]

hw/mysite/sns/urls.py
from django.conf.urls import url
from . import views

app_name = 'sns'
urlpatterns = [
    url(r'^(\d*)$', views.index, name='index'),
    url(r'^facebook/friends_ranking/$', views.friends_ranking, name='friends_ranking'),
    url(r'^facebook/save_friends/$', views.save_friends, name='save_friends'),
]

hw/mysite/video/urls.py
from django.conf.urls import url
from . import views

app_name = 'video'

urlpatterns = [
    url(r'^(\d*)$', views.main_list, name='main_list'),
    url(r'^cate/new/$', views.cate_new, name='cate_new'),
    url(r'^video/search/$', views.search, name='search'),
    url(r'^video/add/$', views.video_add, name='video_add'),
    url(r'^video/edit/(\d+)/$', views.video_edit, name='video_edit'),
]

hw/mysite/video/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=32, unique=True)
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Video(models.Model):
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    kind = models.CharField(max_length=100)
    key = models.CharField(max_length=100)
    title = models.CharField(max_length=100)
    desc = models.TextField(blank=True)
    published_date = models.DateTimeField()
    thumbnail = models.URLField(blank=True)
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

hw/mysite/video/forms.py
from django import forms
from .models import Category, Video


class CateForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('name', )

class VideoAddForm(forms.ModelForm):
    class Meta:
        model = Video
        fields = ('kind', 'key',
                  'title', 'desc',
                  'published_date', 'thumbnail')

        widgets = {'kind': forms.HiddenInput(),
                   'key': forms.HiddenInput(),
                   'title': forms.HiddenInput(),
                   'desc': forms.HiddenInput(),
                   'published_date': forms.HiddenInput(),
                   'thumbnail': forms.HiddenInput(),
                   }
    
class VideoForm(forms.ModelForm):
    class Meta:
        model = Video
        fields = ('category', 'title', 'desc', 'key', )
        widgets = {
            'category': forms.Select( attrs={'class': 'form-control'}),
            'title': forms.TextInput( attrs={'class': 'form-control'}),
            'desc': forms.TextInput( attrs={'class': 'form-control'}),
            'key': forms.HiddenInput(),
            'thumbnail': forms.HiddenInput(),
        }

hw/mysite/video/views/bookmark.py
from django.shortcuts import redirect, render, get_object_or_404
from video.models import Category, Video
from video.forms import VideoAddForm, VideoForm

__all__ = ['video_add', 'video_edit']


def video_add(request):
    if request.method != 'POST':
        return redirect( 'video:search' )

    # 훗. pk=1 이라니
    cate = get_object_or_404( Category, pk=1 )

    next = request.POST.get( 'next' )
    form = VideoAddForm(request.POST)

    if not form.is_valid():
        print( 'form invalid' )
        print( form )
        return redirect(next)

    video = form.save(commit=False)
    video.category = cate
    video.save()

    return redirect(next)


def video_edit(request, video_id ):
    video = get_object_or_404( Video, pk=video_id )
    cate = video.category

    context = {
        'sub_title': 'Edit Video',
        'key': video.key,
    }

    if request.method != 'POST':
        form = VideoForm( instance=video )
        context['form'] = form
        return render( request, 'video/video_edit.html', context )

    form = VideoForm(request.POST, instance=video)
    if not form.is_valid():
        context['form'] = form
        return render( request, 'video/video_edit.html', context )

    video = form.save( commit=False )
    video.save()

    return redirect( 'video:main_list', video.category.id )

hw/mysite/video/views/search.py
from django.shortcuts import render
from django.utils.dateparse import parse_datetime
from video.apis.youtube import youtube_search

from video.forms import VideoAddForm

__all__ = ['search']


def search(request):
    context = {}

    keyword = request.GET.get('keyword')
    page_token = request.GET.get('page_token')

    if not keyword:
        return render(request, 'video/search.html', context)

    response = youtube_search(keyword, page_token)

    context['keyword'] = keyword
    context['response'] = response

    # form_list = []
    # for item in response['items']:
    #     print(item['kind'])
    #     print(item['id'])
    #
    #     form = VideoAddForm(
    #         initial={'kind': item['kind'],
    #                  'key': item['id'],
    #                  'title': item['snippet']['title'],
    #                  'desc': item['snippet']['description'],
    #                  'published_date': parse_datetime(
    #                      item['snippet']['publishedAt']),
    #                  'thumbnail': item['snippet']['thumbnails']['medium']['url'],
    #                  })
    #
    #     form_list.append(form)
    #
    # context['form_list'] = form_list

    return render(request, 'video/search.html', context)

hw/mysite/templates/video/cate_edit.html
{% extends 'common/base.html' %}

{% block content %}
<div class="container">
<h4>{{ sub_title }}</h4>
<form method="POST">
{% csrf_token %}
{{ form.as_p }}
<button type="submit" class="save btn btn-default">Save</button>
</form>
</div>
{% endblock %}

hw/mysite/templates/video/index.html
{% extends 'common/base.html' %}

{% block content %}
<div class="container">
<ul class="nav nav-pills">
  <li role="presentation"
    {% if cur_id == 0 %}class="active"{% endif %}>
    <a href="{% url 'video:main_list' ''%}">전체</a>
  </li>
  {% for cate in cate_list %}
  <li role="presentation"
    {% if cur_id == cate.id %}class="active"{% endif %}>
    <a href="{% url 'video:main_list' cate.id %}">{{ cate.name }}</a>
  </li>
  {% endfor %}
  <li role="presentation">
    <a href="{% url 'video:cate_new' %}">
      <span class="glyphicon glyphicon-plus"></span>
    </a>
  </li>
</ul>

{% for video in video_list %}
<div class="panel panel-default">
  <div class="panel-heading">
    <span class="panel-title">{{ video.title }}</span>
    <a href="{% url 'video:video_edit' video.id %}">
      <span class="glyphicon glyphicon-pencil"></span></a>
    <div class="panel-body margin-top10 embed-responsive embed-responsive-16by9">
      <!--
      <iframe width="560" height="315"
              src="https://www.youtube.com/embed/{{ video.key }}"
              frameborder="0" allowfullscreen>
      </iframe>
      -->
      <iframe class="embed-responsive-item" width="560" height="315"
              src="https://www.youtube.com/embed/{{ video.key }}"
              allowfullscreen>
      </iframe>
    </div>
  </div>
</div>
{% endfor %}
</div>
{% endblock %}

hw/mysite/templates/video/search.html
{% extends 'common/base.html' %}
{% load app_filters %}
{% block content %}
<div class="container">

  <div class="row">
    <form action="">
      <div class="col-sm-offset-2 col-sm-8">
        <div class="input-group">
          <input type="text" class="form-control"
            name="keyword" placeholder="{{ keyword }}">
          <span class="input-group-btn">
            <button class="btn btn-default" type="submit">검색</button>
          </span>
        </div>
      </div>
    </form>
  </div>
  <p></p>

  <p></p>
  <ul class="media-list">
    {% for item in response.items %}
    <li class="media">
      <div class="media-left">
        <a href="#">
          <img src="{{ item.snippet.thumbnails.medium.url }}">
        </a>
      </div>
      <div class="media-body">
        <h4 class="media-heading">{{ item.snippet.title }}</h4>
        <p>{{ item.snippet.description|truncatewords:80 }}</p>
        <p>{{ item.snippet.publishedAt|str2date|date:'Y-m-d H:i:s' }}</p>

        {% if item.exist %}
        <button class="btn btn-warning">등록된 영상</button>
        {% else %}
        <form action="{% url 'video:video_add' %}" method="POST">
          {% csrf_token %}
          <input type="hidden" name="kind" value="{{ item.kind }}">
          <input type="hidden" name="key" value="{{ item.id }}">
          <input type="hidden" name="title" value="{{ item.snippet.title }}">
          <input type="hidden" name="desc" value="{{ item.snippet.description }}">
          <input type="hidden" name="published_date" value="{{ item.snippet.publishedAt|str2date|date:'Y-m-d H:i:s' }}">
          <input type="hidden" name="thumbnail" value="{{ item.snippet.thumbnails.medium.url }}">

          <input type="hidden" name="next" value="{{ request.get_full_path }}">
          <button type="submit" class="btn btn-primary">북마크에 추가</button>
        </form>
        {% endif %}
      </div>
    </li>
    {% endfor %}
  </ul>

  <nav>
    <ul class="pager">
      {% if response.prevPageToken %}
      <li><a href="{% url 'video:search' %}?keyword={{ keyword }}&page_token={{ response.prevPageToken}}">이전페이지</a></li>
      <li><a href="{% url 'video:search' %}?keyword={{ keyword }}">첫 페이지로</a></li>
      {% endif %}
      {% if response.nextPageToken %}
      <li><a href="{% url 'video:search' %}?keyword={{ keyword }}&page_token={{ response.nextPageToken}}">다음페이지</a></li>
      {% endif %}
    </ul>
  </nav>
</div>
{% endblock %}

hw/mysite/templates/video/video_edit.html
{% extends 'common/base.html' %}
{% load staticfiles %}

{% block content %}
<div class="container">
<h4>{{ sub_title }}</h4>

<form method="POST" class="form">
{% csrf_token %}
{% for field in form %}
<div class="form-group {% if field.errors %}has-error{% endif %}">
  {{ field.label_tag }}
  {{ field }}
  <div>{{ field.errors }}</div>
</div>
{% endfor %}
<button type="submit" class="save btn btn-default">Save</button>
<!-- <button type="button" class="btn btn-default" onclick="applyUrl()">
  Preview</button> -->
</form>
</div>

<p></p>
<div class="panel panel-default">
<div id="id_preview_panel" class="panel-body embed-responsive embed-responsive-16by9">
  {% if key %}
  <iframe class="embed-responsive-item" width="560" height="315"
          src="https://www.youtube.com/embed/{{ key }}"
          allowfullscreen>
  </iframe>
  {% endif %}
</div>
</div>
<!-- <script src="{% static 'js/video_edit.js' %}"></script> -->

{% endblock %}