hw/mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'', include('video.urls')),
    url(r'^member/', include('member.urls')),
    url(r'^sns/', include('sns.urls')),
    url(r'^admin/', admin.site.urls),
]

hw/mysite/sns/urls.py
from django.conf.urls import url
from . import views

app_name = 'sns'
urlpatterns = [
    url(r'^(\d*)$', views.index, name='index'),
    url(r'^facebook/friends_ranking/$', views.friends_ranking, name='friends_ranking'),
    url(r'^facebook/save_friends/$', views.save_friends, name='save_friends'),
]

hw/mysite/sns/models.py
from django.db import models


class FaceRanking(models.Model):
    created_date = models.DateTimeField(auto_now_add=True, db_index=True)
    comment = models.CharField(max_length=100,blank=True)

    def __str__(self):
        return self.created_date.strftime('%Y-%m-%d %H:%M:%S')


class FaceFriend(models.Model):
    face_ranking = models.ForeignKey(FaceRanking, on_delete=models.CASCADE)
    face_id = models.CharField(max_length=32)
    face_name = models.CharField(max_length=100)
    score = models.IntegerField()

hw/mysite/sns/views/facebook.py
import time
import datetime
import json
import requests

from django.contrib import messages
from django.utils import timezone
from django.shortcuts import redirect, render

from member.apis import facebook


__all__ = [
    'friends_ranking',
]


def friends_ranking(request):
    if request.GET.get('error'):
        messages.success(request, '페이스북 친구확인을 취소하셨습니다.')
        return redirect('sns:index', '')

    if not request.GET.get('code'):
        messages.error(request, '페이스북 로그인에 실패하였습니다.')
        return redirect('sns:index', '')

    code = request.GET.get('code')
    redirect_uri = request.build_absolute_uri(request.path)

    access_token = facebook.get_access_token(code, redirect_uri)
    if not access_token:
        messages.info(request, '페이스북 로그인이 만료되었습니다.')
        return redirect('sns:index', '')

    user_id = facebook.get_user_id_from_token(access_token)

    one_year_ago = timezone.now() - datetime.timedelta(days=365)
    since = int(time.mktime(one_year_ago.timetuple()))
#    print(since)
    
    url_user_feed = 'https://graph.facebook.com/v2.8/{}/feed' \
                    '?access_token={}' \
                    '&fields=from,comments{{from,comments}}' \
                    '&since={}'.format(
                        user_id, access_token, since )

#    print( url_user_feed )
    messages.info( request, url_user_feed )

    # 'facebook_id':count dictionary
    friends_score = {}
    friends_name = {}


#     while True :
#         r = requests.get(url_user_feed)
#         rsp_user_feed = r.json()
#
# #        json_data = json.dumps(rsp_user_feed, indent=2)
# #        print(json_data)
#
#         rsp_data0 = rsp_user_feed.get('data')
#         if not rsp_data0: break
#
#         for item0 in rsp_data0:
#             for key0,val0 in item0.items():
#                 if key0 == 'from':
#                     id = val0.get('id')
#                     if id: accum_score(friends_score, id)
#                     name = val0.get('name')
#                     if name: friends_name[id] = name
#                 elif key0 == 'comments':
#                     rsp_data1 = val0.get('data')
#                     if not rsp_data1: break
#
#                     for item1 in rsp_data1:
#                         for key1,val1 in item1.items():
#                             if key1 == 'from':
#                                 id = val1.get('id')
#                                 if id: accum_score(friends_score, id)
#                                 name = val1.get('name')
#                                 if name: friends_name[id] = name
#                             elif key1 == 'comments':
#                                 rsp_data2 = val1.get('data')
#                                 if not rsp_data2: break
#
#                                 for item2 in rsp_data2:
#                                     for key2,val2 in item2.items():
#                                         if key2 == 'from':
#                                             id = val2.get('id')
#                                             if id: accum_score(friends_score, id)
#                                             name = val2.get('name')
#                                             if name: friends_name[id] = name
#
#         rsp_paging = rsp_user_feed.get('paging')
#         if not rsp_paging:
#             break
#
#         rsp_next = rsp_paging.get('next')
#         if not rsp_next:
#             break
#
#         url_user_feed = rsp_next


    while True:
        r = requests.get(url_user_feed)
        rsp_user_feed = r.json()

        main_data = rsp_user_feed.get('data')
        if not main_data: break

        proc_data(friends_score, friends_name, main_data)

        rsp_paging = rsp_user_feed.get('paging')
        if not rsp_paging:
            break

        rsp_next = rsp_paging.get('next')
        if not rsp_next:
            break

        url_user_feed = rsp_next

    friend_list = [(id, friends_name[id], score) \
                    for id,score in friends_score.items()]
#    print(friend_list)
    friend_list = sorted(friend_list, key=lambda x: (x[2],x[1]), reverse=True)
#    print(friend_list)
    friend_list = friend_list[:50]

    context = {
        'access_token': access_token,
        'friend_list': friend_list,
        }

    return render(request, 'sns/friends_ranking.html', context)


def proc_data(friends_score, friends_name, data):
    for item in data:
        for key,val in item.items():
            if key == 'from':
                id = val.get('id')
                if id: accum_score(friends_score, id)
                name = val.get('name')
                if name: friends_name[id] = name
            elif key == 'comments':
                com_data = val.get('data')
                if not com_data: break

                proc_data(friends_score, friends_name, com_data)


def accum_score( friends_score, id ):
    score = friends_score.get(id)
    if score:
        score += 1
    else:
        score = 1

#    print( id, score )
    friends_score[id] = score

hw/mysite/sns/views/index.py
from django.shortcuts import render, get_object_or_404
from django.conf import settings

from sns.models import FaceRanking, FaceFriend


__all__ = [
    'index',
]

def index(request, rank_id):
    if rank_id is '':
        rank_id = 0
    else:
        rank_id = int(rank_id)

    if rank_id > 0:
        rank = get_object_or_404(FaceRanking, pk=rank_id)
    else:
        rank = None

    rank_list = get_rank_list(rank, 2)
    if rank_list and not rank:
        rank = rank_list[-1]
        
    if not rank:
        return render(request, 'sns/index.html', {})
    
    if rank_list.index(rank) > 1:
        prev_rank = rank_list[rank_list.index(rank)-1]
    else:
        prev_rank = None

    friend_list = list(
            rank.facefriend_set.order_by('-score', '-face_name')[:50])
    if prev_rank:
        prev_list = list(
                prev_rank.facefriend_set.order_by('-score', '-face_name')[:50])
        make_updown( friend_list, prev_list )

    context = {
        'facebook_app_id': settings.FACEBOOK_APP_ID,
        'cur_rank': rank,
        'rank_list': rank_list,
        'friend_list': friend_list,
    }
    return render(request, 'sns/index.html', context)


def find_index(friend_list, face_id):
    for i, friend in enumerate(friend_list):
        if friend.face_id == face_id:
            return i

    return -1


def make_updown( friend_list, prev_list ):
    for i, friend in enumerate(friend_list):
        prev_index = find_index(prev_list, friend.face_id)
        if prev_index < 0:
            friend.updown = 1000
        else:
            friend.updown = prev_index - i


def get_rank_list(cur_rank=None, count_each=5):
    if not cur_rank:
        tot_count = count_each * 2 + 1
        rank_list = list(FaceRanking.objects.order_by('-created_date')[:tot_count])
        rank_list.reverse()
        return rank_list

    count_before = FaceRanking.objects.filter(
                        created_date__lt=cur_rank.created_date).count()
    count_behind = FaceRanking.objects.filter(
                        created_date__gt=cur_rank.created_date).count()

    print(count_each,count_before,count_behind)
    if count_before < count_each:
        count_behind = min(count_behind, count_each * 2 - count_before)
    elif count_behind < count_each:
        count_before = min(count_before, count_each * 2 - count_behind)
    else:
        count_before = min(count_before, count_each)
        count_behind = min(count_behind, count_each)

    print(count_each,count_before,count_behind)

    rank_list = [cur_rank]

    if count_before > 0:
        before_list = FaceRanking.objects.\
                    filter(created_date__lt=cur_rank.created_date).\
                    order_by('-created_date')[:count_before]
        before_list = list(before_list)
        before_list.reverse()
        rank_list = before_list + rank_list

    if count_behind > 0:
        behind_list = FaceRanking.objects.\
                    filter(created_date__gt=cur_rank.created_date).\
                    order_by('created_date')[:count_behind]
        behind_list = list(behind_list)
        rank_list = rank_list + behind_list

    return rank_list

hw/mysite/sns/views/save.py
from django.contrib import messages
from django.shortcuts import redirect
from sns.models import FaceRanking, FaceFriend

__all__ = [
    'save_friends',
    ]

def save_friends(request):
    if request.method != 'POST':
        return redirect('sns:index', '')

    friend_count = request.POST.get('friend_count')
    if not friend_count:
        messages.error(request, 'missing field friend_count')
        return redirect('sns:index', '')

    friend_count = int(friend_count)
    new_rank = FaceRanking.objects.create(comment="...")
    for i in range(friend_count):
        field_id = 'id_{:02d}'.format(i)
        field_name = 'name_{:02d}'.format(i)
        field_score = 'score_{:02d}'.format(i)

        value_id = request.POST.get(field_id)
        value_name = request.POST.get(field_name)
        value_score = request.POST.get(field_score)

        new_friend = FaceFriend.objects.create(
                face_ranking=new_rank,
                face_id=value_id,
                face_name=value_name,
                score=int(value_score) )

    return redirect('sns:index', '')

hw/mysite/templates/sns/friends_ranking.html
{% extends 'common/base.html' %}

{% block content %}
<div class="container">
{% if friend_list %}
<div class="form">
<form action="{% url 'sns:save_friends' %}" method="POST">
  {% csrf_token %}
  <input type="hidden" name="friend_count" value="{{ friend_list|length }}">
  {% for friend in friend_list %}
    {% with cur_index=forloop.counter0|stringformat:"02d" %}
    <input type="hidden" name="id_{{ cur_index }}" value="{{ friend.0 }}">
    <input type="hidden" name="name_{{ cur_index }}" value="{{ friend.1 }}">
    <input type="hidden" name="score_{{ cur_index }}" value="{{ friend.2 }}">
    {% endwith %}
  {% endfor %}
  <button type="submit" class="btn btn-warning">Best Friends 저장</button>
</form>
</div>

{% for friend in friend_list %}
<div class="media">
  <div class="media-left">
    <img src="https://graph.facebook.com/v2.8/{{ friend.0 }}/picture?access_token={{ access_token }}&type=large">
  </div>
  <div class="media-body">
    <h5 class="media-heading">
      {{ friend.1 }}
    </h5>
    <p>{{ friend.2 }}</p>
  </div>
</div>
{% endfor %}
{% else %}
<h3>친구가 없습니다. OTL ㅠㅠ</h3>
{% endif %}
</div>
{% endblock %}

hw/mysite/templates/sns/index.html
{% extends 'common/base.html' %}

{% block content %}
<div class="container">
<h3>SNS Application</h3>
<div class="btn-group">
  <button type="button"
    class="btn btn-danger dropdown-toggle {% if not cur_rank %}disabled{% endif %}"
    data-toggle="dropdown" aria-expanded="false">
    과거 {% if cur_rank %}{{ cur_rank }}{% else %}페북 친구없음{% endif %}<span class="caret"></span>
  </button>
  <ul class="dropdown-menu" role="menu">
    {% for rank in rank_list %}
    <li><a href="{% url 'sns:index' rank.id %}">
      {{ rank }}
      {%if rank == cur_rank %}
      <span class="glyphicon glyphicon-heart"></span>{% endif %}
    </a></li>
    {% endfor %}
  </ul>
</div>
  <a href="https://www.facebook.com/v2.8/dialog/oauth?client_id={{ facebook_app_id }}&redirect_uri=http://{{ request.META.HTTP_HOST }}{% url 'sns:friends_ranking' %}&response_type=code&scope=user_friends,public_profile,email,user_posts"
    class="btn btn-warning">다시 페이스북 친구확인
    <span class="badge">없을 수도 있다OTL</span>
  </a>
<p></p>
<div>
{% if not friend_list %}
<div class="alert alert-info" role="alert">
친구가 하나도 없습니다.
</div>
{% else %}
<table class="table">
  <tr><th>#</th> <th></th> <th>친구 이름</th> <th>친구 점수</th> <th>순위 변화</th></tr>
  {% for friend in friend_list %}
  <tr>
    <th>{{ forloop.counter }}</th>
    <td><img src="https://graph.facebook.com/v2.8/{{ friend.face_id }}/picture?access_token={{ access_token }}&type=large"></td>
    <td>{{ friend.face_name }}</td>
    <td>{{ friend.score }}</td>
    <td>
      {% if not friend.updown %}-
      {% elif friend.updown == 0 %}-
      {% elif friend.updown == 1000 %}New
      {% elif friend.updown > 0 %}{{ friend.updown }}<span class="glyphicon glyphicon-thumbs-up"></span>
      {% else %}{{ friend.updown }}<span class="glyphicon glyphicon-thumbs-down"></span>
      {% endif %}
    </td>

  </tr>
  {% endfor %}
</table>
{% endif %}
</div>

</div>
{% endblock %}