cls/django/tutorial/django/polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^(?P<q_id>\d+)/$', views.detail, name='detail' ),
	url(r'^(?P<q_id>\d+)/results/$', views.results, name="results" ),
	url(r'^(?P<q_id>\d+)/vote/$', views.vote, name="vote" ),
	url(r'^(?P<q_id>\d+)/add_choice/$', views.add_choice, name="add_choice" ),
]

cls/django/tutorial/django/polls/models.py
import datetime
from django.db import models
from django.utils import timezone


# Create your models here.
class Question(models.Model):
	question_text = models.CharField('질문 내용', max_length=200)
	pub_date = models.DateTimeField('date published')

	def was_published_recently(self):
		return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

	def __str__(self):
		return "질문 [{}]".format( self.question_text )

class Choice(models.Model):
	question = models.ForeignKey(Question,on_delete=models.CASCADE )
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)

	def __str__(self):
		return "선택 [{}]".format( self.choice_text )

cls/django/tutorial/django/polls/views.py
from django.shortcuts import get_object_or_404, render

# Create your views here.

from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.template import loader
from django.urls import reverse

from .models import Question

def index(request):
	q_list = Question.objects.order_by( '-pub_date' )[:5]
	context = {
		'q_list': q_list,
	}
	return render( request, 'index.html', context )

def index_old(request):
	q_list = Question.objects.order_by( '-pub_date' )[:5]
	template = loader.get_template( 'index.html' )
	context = {
		'q_list': q_list,
	}
	return HttpResponse( template.render( context, request ) )
#	output = '<br>\n'.join( [q.question_text for q in q_list] )
#	return HttpResponse( output )

#	return HttpResponse( "Hello, world. You're at the polls index." )

def detail( request, q_id ):
	q = get_object_or_404( Question, pk=q_id )
	return render( request, 'detail.html', {'question':q } )

def detail_old(request, q_id ):
	try:
		q = Question.objects.get( pk=q_id )
	except Question.DoesNotExist:
		raise Http404( "Question does not exist" )
	return render( request, 'detail.html', {'question':q } )

#	return HttpResponse( "You're looking at question {}.".format( q_id ) )


def results(request, q_id ):
	q = get_object_or_404( Question, pk=q_id )
	return render( request, 'results.html', { 'question':q } )

#	return HttpResponse( "You're looking at the results of question {}.".format( q_id ) )

def vote( request, q_id ):
	question = get_object_or_404( Question, pk=q_id )
	try:
		selected_choice = question.choice_set.get( pk=request.POST['choice'] )
	except( KeyError, Choice.DoesNotExist ):
		con = {
			'question': question,
			'error_message': "You didn't select a choice.",
		}
		return render( request, 'detail.html', con )
	else:
		selected_choice.votes += 1
		selected_choice.save()

		return HttpResponseRedirect(
					 reverse( 'polls:results', args=(question.id,) ) )

#	return HttpResponse( "You're voting on question {}.".format( q_id ) )

def add_choice( request, q_id ):
	question = get_object_or_404( Question, pk=q_id )
	try:
		choice_name = request.POST['new_choice']
	except KeyError:
		con = {
			'question': question,
			'error_message': "You didn't input new choice.",
		}
		return render( request, 'detail.html', con )

	nameLen = len(choice_name)
	if nameLen <= 0 or nameLen > 200:
		con = {
			'question': question,
			'error_message': "You didn't input valid choice.",
		}
		return render( request, 'detail.html', con )

	choice_list = question.choice_set.filter( choice_text=choice_name )
	choice_count = len(choice_list)
	if choice_count != 0:
		con = {
			'question': question,
			'error_message': "Same choice[{}] already exist!!! LOOK AGAIN!!!".
								format( choice_name ),
		}
		return render( request, 'detail.html', con )
	
	c = question.choice_set.create( choice_text=choice_name, votes=0 )
	
	return HttpResponseRedirect(
					 reverse( 'polls:detail', args=(question.id,) ) )

cls/django/tutorial/django/polls/templates/detail.html
<h1>
{{ question.question_text }}
</h1>

{% if error_message %}
<p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
	<input type="radio" name="choice" id="choice{{ forloop.counter }}"
			 value="{{ choice.id }}">
	<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

<h3>Do you want another choice?</h3>
<form action="{% url 'polls:add_choice' question.id %}" method="post">
{% csrf_token %}
	<label for="new_choice">New Choice</label>
	<input type="text" id="new_choice" name="new_choice" size=20><br>
<input type="submit" value="Add">
</form>

cls/django/tutorial/django/polls/templates/index.html
{% if q_list %}
<ul>
	{% for q in q_list %}
		<li><a href="{% url 'polls:detail' q.id %}">{{ q.question_text }}</a></li>
	{% endfor %}
</ul>
{% else %}
<p>No polls are available.</p>
{% endif %}

cls/django/tutorial/django/polls/templates/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
	<li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>